<template>
  <a-spin :spinning="loading" tip="正在加载测试结果…">
    <div class="section">
      <div class="section-header"><div><h2 class="section-title">Kimi 能力测试结果</h2><p class="subtitle">{{ data?.config?.model || 'kimi-k3' }} · {{ protocolText }} · {{ statusText }}</p></div><a-button @click="router.push('/tests/kimi-suite')">再次测试</a-button></div>
      <div class="section-body"><div class="progress-head"><strong>实时测试进度</strong><span>{{ completedCount }} / {{ totalCount }} Case</span></div><a-progress :percent="progressPercent" :status="progressStatus" :stroke-width="8"/><p class="current-line"><span class="live-dot" :class="{ active: isRunning }"/>当前 Case：{{ data?.progress?.current_case || (isTerminal ? '已结束' : '等待开始') }}　场景：{{ data?.progress?.current_scenario || '—' }}</p></div>
    </div>
    <div class="section">
      <div class="section-header"><h2 class="section-title">Case 实时结果</h2><a-tag :color="isTerminal ? 'green' : 'processing'">{{ isTerminal ? '结果已落盘' : '每 1.5 秒刷新' }}</a-tag></div>
      <div class="section-body table-wrap">
        <a-table :columns="columns" :data-source="liveCases" :pagination="false" :scroll="{ x: 1300 }" row-key="case_id" size="middle" :custom-row="rowProps">
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'endpoint'">{{ data?.config?.endpoint || '—' }}</template><template v-else-if="column.key === 'apiKey'">已脱敏</template><template v-else-if="column.key === 'model'">{{ data?.config?.model || '—' }}</template>
            <template v-else-if="column.key === 'status'"><a-tag :color="statusColor(record.status)">{{ statusLabel(record.status) }}</a-tag></template><template v-else-if="column.key === 'elapsed'">{{ record.elapsed_sec ? `${Number(record.elapsed_sec).toFixed(3)}s` : '—' }}</template><template v-else-if="column.key === 'ttft'">{{ record.ttft_sec ? `${Number(record.ttft_sec).toFixed(3)}s` : '—' }}</template><template v-else-if="column.key === 'retry'">{{ record.retry_count || 0 }}</template><template v-else-if="column.key === 'rerun'">{{ record.manual_rerun_count || 0 }}</template><template v-else-if="column.key === 'failure'">{{ failureReason(record) }}</template>
          </template>
        </a-table>
      </div>
    </div>
    <div v-if="summary" class="section"><div class="section-header"><h2 class="section-title">场景证据</h2></div><div class="section-body"><div v-for="item in summary.cases" :key="item.case_id" class="detail"><h3>{{ item.case_name }}</h3><a-descriptions v-for="scenario in item.scenarios" :key="scenario.scenario_id" :column="3" bordered><a-descriptions-item label="场景">{{ scenario.scenario_name }}</a-descriptions-item><a-descriptions-item label="状态"><a-tag :color="statusColor(scenario.status)">{{ statusLabel(scenario.status) }}</a-tag></a-descriptions-item><a-descriptions-item label="耗时">{{ Number(scenario.latency_sec || 0).toFixed(3) }}s</a-descriptions-item></a-descriptions></div></div></div>
    <a-drawer v-model:open="drawerOpen" :title="selectedCase?.case_name || 'Case 详情'" placement="right" :width="Math.min(620, windowWidth - 24)" destroy-on-close>
      <template v-if="selectedCase">
        <div class="drawer-meta"><a-tag :color="statusColor(selectedCase.status)">{{ statusLabel(selectedCase.status) }}</a-tag><span>{{ protocolText }}</span><span>{{ data?.config?.model || '—' }}</span></div>
        <a-descriptions :column="2" bordered size="small"><a-descriptions-item label="Endpoint">{{ data?.config?.endpoint || '—' }}</a-descriptions-item><a-descriptions-item label="耗时">{{ Number(selectedCase.elapsed_sec || 0).toFixed(3) }}s</a-descriptions-item><a-descriptions-item label="首 token">{{ selectedCase.ttft_sec ? `${Number(selectedCase.ttft_sec).toFixed(3)}s` : '—' }}</a-descriptions-item><a-descriptions-item label="重试">{{ selectedCase.retry_count || 0 }}</a-descriptions-item></a-descriptions>
        <div v-for="scenario in selectedCase.scenarios || []" :key="scenario.scenario_id" class="scenario-block"><div class="scenario-title"><strong>{{ scenario.scenario_name }}</strong><a-tag :color="statusColor(scenario.status)">{{ statusLabel(scenario.status) }}</a-tag></div><div class="evidence-row"><span>请求 URL</span><code>{{ data?.config?.base_url || '' }}{{ data?.config?.endpoint || '' }}</code></div><div v-if="scenario.evidence?.token_evidence" class="token-evidence"><span>本地估算 <b>{{ scenario.evidence.token_evidence.local_prompt_tokens ?? '—' }}</b></span><span>上游输入 <b>{{ scenario.evidence.token_evidence.upstream_input_tokens ?? '—' }}</b></span><span>差值 <b>{{ scenario.evidence.token_evidence.delta_tokens ?? '—' }}</b></span><span>比例 <b>{{ scenario.evidence.token_evidence.delta_ratio == null ? '—' : `${(scenario.evidence.token_evidence.delta_ratio * 100).toFixed(1)}%` }}</b></span></div><pre class="evidence-code">{{ formatEvidence(scenario) }}</pre><p v-if="scenario.assertion?.detail" class="assertion-detail">{{ scenario.assertion.detail }}</p></div>
      </template>
    </a-drawer>
  </a-spin>
</template>
<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Button as AButton, Descriptions as ADescriptions, Drawer as ADrawer, Progress as AProgress, Spin as ASpin, Table as ATable, Tag as ATag } from 'ant-design-vue'
import { getKimiSuite } from '../api/client'
const props=defineProps({id:{type:String,required:true}}); const router=useRouter(); const data=ref(null); const loading=ref(false); let timer
const terminalStatuses=['completed','failed','cancelled','interrupted']
const columns=[{title:'Case 名称',dataIndex:'case_name',key:'case_name',width:250},{title:'Endpoint',key:'endpoint',width:190},{title:'API Key',key:'apiKey',width:110},{title:'供应商模型',key:'model',width:150},{title:'状态',key:'status',width:110,align:'center'},{title:'耗时',key:'elapsed',width:105,align:'center'},{title:'首 token',key:'ttft',width:105,align:'center'},{title:'重试',key:'retry',width:75,align:'center'},{title:'人工重跑',key:'rerun',width:100,align:'center'},{title:'失败原因',key:'failure',width:260}]
const summary=computed(()=>data.value?.summary); const isTerminal=computed(()=>terminalStatuses.includes(data.value?.task_status)); const isRunning=computed(()=>data.value?.task_status==='running'); const liveCases=computed(()=>data.value?.progress?.cases||summary.value?.cases||[]); const selectedCaseId=ref(null); const drawerOpen=ref(false); const windowWidth=window.innerWidth
const selectedCase=computed(()=>liveCases.value.find(item=>item.case_id===selectedCaseId.value))
const totalCount=computed(()=>Number(data.value?.progress?.total_cases||summary.value?.results?.total_cases||liveCases.value.length||0)); const completedCount=computed(()=>Number(data.value?.progress?.completed_cases??liveCases.value.filter(item=>!['pending','running'].includes(item.status)).length)); const statusText=computed(()=>({queued:'排队中',running:'运行中',completed:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断'}[data.value?.task_status]||data.value?.task_status||'加载中')); const protocolText=computed(()=>({openai:'OpenAI-compatible',anthropic:'Anthropic Messages',gemini:'Gemini API'}[data.value?.config?.api_protocol]||data.value?.config?.api_protocol||'OpenAI-compatible')); const progressPercent=computed(()=>totalCount.value?Math.min(100,Math.round(completedCount.value/totalCount.value*100)):(summary.value?100:0)); const progressStatus=computed(()=>data.value?.task_status==='failed'?'exception':data.value?.task_status==='completed'?'success':undefined)
function statusLabel(status){return({pending:'待测试',running:'测试中',passed:'通过',suspected_injection:'疑似提示词注入',failed:'失败',unsupported:'接口不支持',unverifiable:'无法判定',request_failed:'请求失败',assertion_failed:'断言失败',cache_hit:'缓存命中',cache_miss:'缓存未命中'}[status]||status||'待测试')} function statusColor(status){return({running:'processing',passed:'success',cache_hit:'success',suspected_injection:'warning',failed:'error',request_failed:'error',assertion_failed:'error',unsupported:'warning',unverifiable:'default',cache_miss:'warning',pending:'default'}[status]||'default')} function failureReason(row){const failed=row.scenarios?.find(item=>!['passed','cache_hit'].includes(item.status));return failed?.assertion?.detail||'—'}
function rowProps(record){return { onClick:()=>{selectedCaseId.value=record.case_id;drawerOpen.value=true} }} function formatEvidence(scenario){return JSON.stringify({request:scenario.request||{},usage:scenario.evidence?.usage||{},token_evidence:scenario.evidence?.token_evidence||null,finish_reason:scenario.evidence?.finish_reason||null,assertion:scenario.assertion||{}},null,2)}
async function load(){try{data.value=await getKimiSuite(props.id);if(!isTerminal.value)timer=window.setTimeout(load,1500)}catch(error){ElMessage.error(error.message);if(!isTerminal.value)timer=window.setTimeout(load,3000)}finally{loading.value=false}} onMounted(()=>{loading.value=true;load()});onBeforeUnmount(()=>window.clearTimeout(timer))
</script>
<style scoped>.progress-head{display:flex;justify-content:space-between;margin-bottom:12px;color:#475569}.current-line{display:flex;align-items:center;margin:18px 0 0}.live-dot{width:9px;height:9px;margin-right:9px;border-radius:50%;background:#94a3b8}.live-dot.active{background:#1677ff;box-shadow:0 0 0 5px rgba(22,119,255,.12);animation:pulse 1.4s infinite}.table-wrap{overflow:hidden}.detail{margin-top:20px}.detail:first-child{margin-top:0}.detail h3{margin-bottom:8px}.drawer-meta{display:flex;gap:12px;align-items:center;margin-bottom:16px;color:#64748b}.scenario-block{margin-top:18px;border-top:1px solid #eef2f6;padding-top:14px}.scenario-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.evidence-row{display:grid;grid-template-columns:72px 1fr;gap:10px;padding:10px 12px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:6px;font-size:12px}.evidence-row code{overflow-wrap:anywhere;color:#334155}.token-evidence{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.token-evidence span{display:grid;gap:4px;padding:10px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:6px;color:#64748b;font-size:12px}.token-evidence b{color:#111827;font-size:15px}.evidence-code{max-height:260px;overflow:auto;margin:10px 0 0;padding:14px;background:#111827;color:#dbeafe;border-radius:7px;font-size:12px;line-height:1.6}.assertion-detail{margin:8px 0 0;color:#b42318;font-size:12px}@keyframes pulse{50%{opacity:.45}}@media(max-width:640px){.token-evidence{grid-template-columns:repeat(2,1fr)}}</style>
